INSERT INTO BTSD_EOBRASHENIYA.AV_APPEALS_APPLICATIONS(TYPE_ID,ISSUE_CATEGORY_ID,SUBISSUE_CATEGORY_ID,ORG_ID,ASSISTANT_USER_ID
,CREATED_DATE
,MODIFIED_DATE
,LANGUAGE_ID
,APPLICANT_ID
,APPEAL_CHARACTER
,ID
,LOCATION_ID
,RESPONSE_GET_WAY
,APPEAL_FORM
,COMPLAINT_APPEAL_ID
,COMPLAINT_ORGANIZATION_ID
,COMPLAINT_LOCATION_ID
,COMPLAINT_EXECUTIVE_USER_ID
,COMPLAINT_TYPE_ID)
VALUES