SELECT
 "id" AS "ID" 
 , "actor_user_id" AS "ACTOR_USER_ID" 
,created_date AS "CREATED_DATE" 
, modified_date AS "MODIFIED_DATE" 
, date AS "DATE" 
, actor_org_id AS "ACTOR_ORG_ID" 
, type AS "TYPE" 
, "state" AS "STATE" 
, "working_state" AS "WORKING_STATE" 
, "message" AS "MESSAGE" 
, "scope" AS "SCOPE" 
, "system_message_ru" AS "SYSTEM_MESSAGE" 
, "files" AS "FILES" 
, "appeal_id" AS "APPEAL_ID" 
, "sign" AS "SIGN" 
FROM public."appeals_history"