SELECT
 "id" AS "ID" 
 , "person_resident" AS "PERSON_RESIDENT" 
, coalesce(TO_CHAR("person_birth_date", 'YYYY-MM-DD'), '0000-00-00')::varchar(10) AS "PERSON_BIRTH_DATE" 
, "person_gender_id" AS "PERSON_GENDER_ID" 
, "person_citizenship_id" AS "PERSON_CITIZENSHIP_ID" 
, "person_nationality_id" AS "PERSON_NATIONALITY_ID" 
, "person_social_status_id" AS "PERSON_SOCIAL_STATUS_ID" 
, "person_occupation_id" AS "PERSON_OCCUPATION_ID" 
, coalesce(TO_CHAR("company_reg_date", 'YYYY-MM-DD'), '0000-00-00')::varchar(10) AS "COMPANY_REG_DATE" 
, "applicants_count" AS "APPLICANTS_COUNT" 
, "attorney_id" AS "ATTORNEY_ID" 
,created_date CREATED_DATE
, modified_date MODIFIED_DATE
, "company_fact_address" AS "COMPANY_FACT_ADDRESS" 
, "company_head_first_name" AS "COMPANY_HEAD_FIRST_NAME" 
, "company_head_second_name" AS "COMPANY_HEAD_SECOND_NAME" 
, "company_head_middle_name" AS "COMPANY_HEAD_MIDDLE_NAME" 
, "company_business_category" AS "COMPANY_BUSINESS_CATEGORY" 
, "company_appeal_out_number" AS "COMPANY_APPEAL_OUT_NUMBER" 
, "mobile_phone" AS "MOBILE_PHONE" 
, "work_home_phone" AS "WORK_HOME_PHONE" 
, "email" AS "EMAIL" 
, "applicant_type" AS "APPLICANT_TYPE" 
, "iinbin" AS "IINBIN" 
, "person_first_name" AS "PERSON_FIRST_NAME" 
, "person_second_name" AS "PERSON_SECOND_NAME" 
, "person_middle_name" AS "PERSON_MIDDLE_NAME" 
, "person_law_address" AS "PERSON_LAW_ADDRESS" 
, "person_fact_address" AS "PERSON_FACT_ADDRESS" 
, "company_name" AS "COMPANY_NAME" 
, "company_law_address" AS "COMPANY_LAW_ADDRESS" 
FROM public."av_applicants"