SELECT 
date_add(hour,12,aa.START_DATE) as start_dt,
aac.ID as appeal_id,
aa.REG_NUMBER as reg_number,
at2.NAME_RU as appeal_type,
ic.NAME_RU as issue,
is2.NAME_RU as subissue,
aa2.IINBIN as iin_bin,
multiIf(aa2.APPLICANT_TYPE='PERSON','Физическое лицо',
aa2.APPLICANT_TYPE='COMPANY','Юридическое лицо',
'') as applicant_type,
if(aa2.APPLICANT_TYPE='PERSON' AND toYear(now())-toInt16(SUBSTRING(COALESCE(aa2.PERSON_BIRTH_DATE,'0'),1,4))<120,toYear(now())-toInt16(SUBSTRING(COALESCE(aa2.PERSON_BIRTH_DATE,'0'),1,4)),
-1) as age,
pc.NAME_RU as citizenship,
pg.NAME_RU as gender,
pn.NAME_RU as nationality,
if(pss.NAME_RU='' OR pss.NAME_RU IS NULL,'Неизвестно',pss.NAME_RU) as social_status,
if(po.NAME_RU='' OR po.NAME_RU IS NULL,'Неизвестно',po.NAME_RU) as occupation,
bc.NAME_RU as company_type
FROM BTSD_EOBRASHENIYA.APPEALS_APPEALS_APPLICATIONS_ACTUAL aac 
LEFT JOIN BTSD_EOBRASHENIYA.APPEALS_ACTUAL aa ON aac.ID=aa.ID
LEFT JOIN BTSD_EOBRASHENIYA.APPEALS_DECISION_ACTUAL ada ON aa.ID=ada.ID
LEFT JOIN BTSD_EOBRASHENIYA.APPEAL_TYPES at2 ON at2.ID=aac.TYPE_ID
LEFT JOIN BTSD_EOBRASHENIYA.ISSUES_CATEGORIES ic ON ic.ID=aac.ISSUE_CATEGORY_ID
LEFT JOIN BTSD_EOBRASHENIYA.ISSUES_SUBCATEGORIES is2 ON is2.ID=aac.SUBISSUE_CATEGORY_ID
LEFT JOIN BTSD_EOBRASHENIYA.APPLICANTS_ACTUAL aa2 ON aa2.ID=aac.APPLICANT_ID
LEFT JOIN BTSD_EOBRASHENIYA.PERSON_CITIZENSHIPS pc ON pc.ID=aa2.PERSON_CITIZENSHIP_ID 
LEFT JOIN BTSD_EOBRASHENIYA.PERSON_GENDERS pg ON pg.ID=aa2.PERSON_GENDER_ID
LEFT JOIN BTSD_EOBRASHENIYA.PERSON_NATIONALITIES pn ON pn.ID=aa2.PERSON_NATIONALITY_ID
LEFT JOIN BTSD_EOBRASHENIYA.PERSON_SOCIAL_STATUSES pss ON pss.ID=aa2.PERSON_SOCIAL_STATUS_ID
LEFT JOIN BTSD_EOBRASHENIYA.PERSON_OCCUPATIONS po ON po.ID=aa2.PERSON_OCCUPATION_ID
LEFT JOIN BTSD_EOBRASHENIYA.BUSINESS_CATEGORY bc ON bc.CODE=aa2.COMPANY_BUSINESS_CATEGORY 
